### ISSUE TITLE
Unable to change the logo and banner images

### ISSUE THREAD

**Issue by ravitalari** [Cezerin2/cezerin2-store#17]
Unable to change the logo and banner images

**Comment by vamcart** [comment]
Looks like problem in cezerin2-client, api.theme.upload method upload images to cezerin2/theme/assets/images folder, but this folder not available from url in browser http://localhost:3001/theme/assets/images

In the docker installation you don't have  this problems because there is nginbx config resolve this problems with folders.

But if you installing from the source code, problem available with logo uploading, slider images uploading.

Maybe we can find the way how to make this work on any installation for cezerin, must work by default at any instlall (docker or source code).

**Comment by vamcart** [comment]
Fixed
